name = "disequi-v4"
main = "src/index.js"
compatibility_date = "2025-01-01"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "none"

[env.production]
name = "disequi-v4-production"

[[env.production.routes]]
pattern = "disequi.com"
custom_domain = true

[[env.production.routes]]
pattern = "www.disequi.com"
custom_domain = true